### ISSUE TITLE
matches-selector dependency broken

### ISSUE THREAD

**Issue by eldh** [metafizzy/outlayer#30]
I got this issue while using react-masonry-mixin, but the problem seems to stem from outlayer. Not really sure why, but desandro-matches-selector just had a new version released, might have something to do with that.

Temporarily worked around this by setting an alias `'matches-selector': 'desandro-matches-selector', ` in webpack, but I thought I'd post in case anyone else had similar problems.

```
ERROR in ../~/react-masonry-mixin/~/masonry/~/outlayer/outlayer.js
Module not found: Error: Cannot resolve module 'matches-selector' in /Users/eldh/Code/quinyx/js/node_modules/react-masonry-mixin/node_modules/masonry/node_modules/outlayer
 @ ../~/react-masonry-mixin/~/masonry/~/outlayer/outlayer.js 993:4-31
```

**Comment by desandro** [comment]
Can you try reinstalling `react-masonry-mixin` again? This should be resolved with `desandro-matches-selector` v1.0.3, which had a bug in its `package.json`

**Comment by eldh** [comment]
Sorry, still the same. The problems seems to be with with 1.0.3 as you say.

**Comment by eldh** [comment]
This is fixed in the newest release. Thanks!
